# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, null=True)),
                ('mob_no', models.IntegerField(null=True)),
                ('email', models.TextField(null=True)),
                ('password', models.TextField(max_length=8, null=True)),
            ],
        ),
    ]
