# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_userdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='user_d',
            new_name='user_detail',
        ),
    ]
