# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170309_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='user_detail',
            new_name='userneme',
        ),
    ]
