# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20170311_0417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='userneme',
            new_name='username',
        ),
    ]
