# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 10:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0007_auto_20170311_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginform',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userloginform',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
