# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20170311_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginform',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
