# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20170311_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginform',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
