# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_userloginform_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginform',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
