# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 11:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0017_auto_20170313_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='username',
        ),
        migrations.RemoveField(
            model_name='userloginform',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userloginform',
            name='username',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='mob_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
