# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20170316_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='mob_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.UserLoginForm'),
        ),
    ]
