# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 11:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0019_auto_20170316_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='mob_no',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='user',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.UserLoginForm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userloginform',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userloginform',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
