# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 16:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20170316_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='username',
        ),
        migrations.AlterField(
            model_name='userloginform',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
